### ISSUE TITLE
problem with Add-FgtFirewallVip and UDP

### ISSUE THREAD

**Issue by poundy** [FortiPower/PowerFGT#112]
I've been trying to add a VIP for a UDP port, and don't get an error but the VIP is always created with TCP instead. Has anyone else tried / tested this?

These two statements are part of a script I am using to create these; as you can see, they're identical in parameters except the -protocol option (I do manipulate the VIP name in $prtname  and the $mappedport and $extport items so they're unique)

    Add-FGTFirewallVip -connection $conn[0] -vdom root -type static-nat -name $prtname `
        -extip $ext_ip -mappedip $mappedip -mappedport $mappedport `
        -comment "Printer for client $($prt.client)" -portforward -protocol UDP -extport $extport 

    Add-FGTFirewallVip -connection $conn[0] -vdom root -type static-nat -name $prtname `
        -extip $ext_ip -mappedip $mappedip -mappedport $mappedport `
        -comment "Printer for client $($prt.client)" -portforward -protocol TCP -extport $extport 

When I execute them, the first one is correct except for it being a TCP not UDP VIP, and the second is always fine. 

I can't see any recent activity in vip.ps1 that looks relevant, and the version I have running was loaded at the beginning of the year in my initial 0.4.1 load.  

Any thoughts, anyone else used it and had different results?

**Comment by alagoutte** [comment]
Hi @poundy,

i don't remember a specific fix for this... and there is a some test on future release with UDP (https://github.com/FortiPower/PowerFGT/blob/master/Tests/integration/FirewallVip.Tests.ps1#L137)

What release of FortiOS do you are using ?
i will try your cmdlet to see if i get the same issue

**Comment by poundy** [comment]
i'm still in 6.0.x world. Still scared by the level of change in 6.2 and 6.4 !

**Comment by alagoutte** [comment]
Ok, found the issue (and there is a quick workaround for you...)

the protocol is case sensible... you need to use -protocol **udp** (and not **UDP**)

**Comment by poundy** [comment]
tested and confirmed ! Thanks !!
