### ISSUE TITLE
Is PowerFGT able to connect to another port than 443 or 80 ?

### ISSUE THREAD

**Issue by NicoRun** [FortiPower/PowerFGT#115]
Hello,

I need to use your Powershell module but when I'm trying to connect my admin Powershell windows, it says :

```powershell
_Unable to connect to FortiGate
At C:\Program Files\WindowsPowerShell\Modules\PowerFGT\0.4.1\Public\Connection.ps1:148 char:13
+             throw "Unable to connect to FortiGate"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Unable to connect to FortiGate:String) [], RuntimeException
+ FullyQualifiedErrorId : Unable to connect to FortiGate_
```
I've checked with the option _-SkipCertificateCheck_, same issue.
I've checked with the option _-httpOnly_, same issue.

Each time, it's asking me to login myself.

I've found that our HTTPS port of our Fortigate another port than 443.
So I ran the cmd :  _Connect-FGT "IpAdress":"otherport" -SkipCertificateCheck_
Same error : 
```powershell
_Unable to connect to FortiGate
At C:\Program Files\WindowsPowerShell\Modules\PowerFGT\0.4.1\Public\Connection.ps1:148 char:13
+             throw "Unable to connect to FortiGate"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Unable to connect to FortiGate:String) [], RuntimeException
+ FullyQualifiedErrorId : Unable to connect to FortiGate_
```

So is it possible to use this module for connecting to Fortigate using a different port for HTTPS connection ?

Thank you in advance.

Regards,

**Comment by NicoRun** [comment]
Hello Alexis,

It works ! Didn't see the options, really sorry for bothering for a trick like that... 

Thank you for the help ! 😊

**Comment by alagoutte** [comment]
no pbl, i will add a note about this parameter ;)
