### ISSUE TITLE
Issue for delete the member of the Policy

### ISSUE THREAD

**Issue by polo38300** [FortiPower/PowerFGT#119]
Hi,

When I use your module for managed the policy of the Fortinet, I have remark that when i launched the command of Remove-FGTFirewallPolicyMember the command is executed without error but the action isn't set.

Also i have a second question about the managed the sequence of the policy rule. Does the module can we managed ther sequence of the policy rule?

Thank in advance for your reponse

Regards,

**Comment by alagoutte** [comment]
> When I use your module for managed the policy of the Fortinet, I have remark that when i launched the command of Remove-FGTFirewallPolicyMember the command is executed without error but the action isn't set.

Strange, how many there is member on the policy ? because there is a "bug" on 0.4.0 if there is 2 members and try to remove one member, it is not remove (you can look #90), it will be fixed on next release (for soon (tm))

> Also i have a second question about the managed the sequence of the policy rule. Does the module can we managed ther sequence of the policy rule?
What do you mean by managed by sequence ? what do you need ?

**Comment by polo38300** [comment]
Bonjour,

Il me semble que j’avais 1 membre dans la règle sur mon Fortinet. Je ferais des tests pour voir si j’ai 3 membres ça se supprime bien.

Concernant ma question portant sur le séquencement des règles. Dès qu’on créé une nouvelle règle celle-ci se créé par défaut en dernière position. Notre besoin serait de pouvoir créer des règles et pouvoir les positionner tout de suite au bon endroit dans notre zone.

Merci pour votre retour.

Paul BOCHARD
Administrateur Système & Réseaux


[cid:image001.png@01D213ED.AA2712B0]
[Sans titre-1]
SITES – Pilotage & Digital / Rhone-Alpes (Ecully)
Groupe NTIC (Nouvelles Technologies de l'Information et de la Communication)
6 Bis, chemin des Muguets
69130 Ecully
Tel : +33 (0)4 37 46 01 84  Fax : +33 (0)4 78 33 81 02
www.sites.fr<http://sites.fr/>
[Sans titre-1]
[cid:image005.jpg@01D6CCAC.4890AAD0]  EXPERTISE    INsTRUMENTATIONS / MESURES    INGENIERIE

• Pour déclarer et suivre vos demandes ou incidents informatiques et télécoms, rendez-vous sur https://support-info.sites.fr<https://support-info.sites.fr/>.


De : Alexis La Goutte <notifications@github.com>
Envoyé : lundi 7 décembre 2020 14:42
À : FortiPower/PowerFGT <PowerFGT@noreply.github.com>
Cc : Paul BOCHARD <Paul.BOCHARD@sites.fr>; Author <author@noreply.github.com>
Objet : Re: [FortiPower/PowerFGT] Issue for delete the member of the Policy (#119)


When I use your module for managed the policy of the Fortinet, I have remark that when i launched the command of Remove-FGTFirewallPolicyMember the command is executed without error but the action isn't set.

Strange, how many there is member on the policy ? because there is a "bug" on 0.4.0 if there is 2 members and try to remove one member, it is not remove (you can look #90<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FFortiPower%2FPowerFGT%2Fissues%2F90&data=04%7C01%7Cpaul.bochard%40sites.fr%7Cea1fcce5cfb843c2358608d89ab5e337%7C70067df4f04645e296ed2f78efb64814%7C0%7C0%7C637429453276674683%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BkyqCYX5o%2FF84qKcVFNHtOa7GoIuOTjqZrKucz3d6iI%3D&reserved=0>), it will be fixed on next release (for soon (tm))

Also i have a second question about the managed the sequence of the policy rule. Does the module can we managed ther sequence of the policy rule?

What do you mean by managed by sequence ? what do you need ?

**Comment by alagoutte** [comment]
Hi,

it is better in english ;-) (but i'm french too)

ok, i will look for sequence policy, do you known what is the command using cli ? can be help for found this

**Comment by polo38300** [comment]
Thank you for your response.

It seems that the command cli is move <id#> [before|after] <id#>

I have a another question for managed the address & address group, you have implement few PowerShell parameter. Do I can you listed the attribute that we want to managed for example the color?

Thank

Regards,

Paul BOCHARD
Administrateur Système & Réseaux


[cid:image001.png@01D213ED.AA2712B0]
[Sans titre-1]
SITES – Pilotage & Digital / Rhone-Alpes (Ecully)
Groupe NTIC (Nouvelles Technologies de l'Information et de la Communication)
6 Bis, chemin des Muguets
69130 Ecully
Tel : +33 (0)4 37 46 01 84  Fax : +33 (0)4 78 33 81 02
www.sites.fr<http://sites.fr/>
[Sans titre-1]
[cid:image006.jpg@01D6CCC3.C44D5620]  EXPERTISE    INsTRUMENTATIONS / MESURES    INGENIERIE

• Pour déclarer et suivre vos demandes ou incidents informatiques et télécoms, rendez-vous sur https://support-info.sites.fr<https://support-info.sites.fr/>.


De : Alexis La Goutte <notifications@github.com>
Envoyé : lundi 7 décembre 2020 17:07
À : FortiPower/PowerFGT <PowerFGT@noreply.github.com>
Cc : Paul BOCHARD <Paul.BOCHARD@sites.fr>; Author <author@noreply.github.com>
Objet : Re: [FortiPower/PowerFGT] Issue for delete the member of the Policy (#119)


Hi,

it is better in english ;-) (but i'm french too)

ok, i will look for sequence policy, do you known what is the command using cli ? can be help for found this

**Comment by alagoutte** [comment]
> It seems that the command cli is move <id#> [before|after] <id#>

Ok, i will look

> I have a another question for managed the address & address group, you have implement few PowerShell parameter. Do I can you listed the attribute that we want to managed for example the color?

There is not (yet) color because i don't use it (and any body ask me), but i think it is easy to implement... (but normality it is feature freeze, i plan to release a new very release soon -> i hope this week...)

**Comment by alagoutte** [comment]
do you have try for member stuff ?

**Comment by polo38300** [comment]
Hi,

This morning, I have tested when I remove several members of the policy. The bug appears just when there are two address group policy. It’s the same issue for remove address policy.

For the managed adress group there are the same bug . I think that these two bugs are linked.

Regards,

Paul BOCHARD
Administrateur Système & Réseaux


[cid:image001.png@01D213ED.AA2712B0]
[Sans titre-1]
SITES – Pilotage & Digital / Rhone-Alpes (Ecully)
Groupe NTIC (Nouvelles Technologies de l'Information et de la Communication)
6 Bis, chemin des Muguets
69130 Ecully
Tel : +33 (0)4 37 46 01 84  Fax : +33 (0)4 78 33 81 02
www.sites.fr<http://sites.fr/>
[Sans titre-1]
[cid:image005.jpg@01D6CEEC.A79127C0]  EXPERTISE    INsTRUMENTATIONS / MESURES    INGENIERIE

• Pour déclarer et suivre vos demandes ou incidents informatiques et télécoms, rendez-vous sur https://support-info.sites.fr<https://support-info.sites.fr/>.


De : Alexis La Goutte <notifications@github.com>
Envoyé : mercredi 9 décembre 2020 20:59
À : FortiPower/PowerFGT <PowerFGT@noreply.github.com>
Cc : Paul BOCHARD <Paul.BOCHARD@sites.fr>; Author <author@noreply.github.com>
Objet : Re: [FortiPower/PowerFGT] Issue for delete the member of the Policy (#119)


do you have try for member stuff ?

**Comment by alagoutte** [comment]
Ok, it is duplicate with #90 and already fixed on #91, it will be available on new release.

For the other feature request, can you open 2 issue (one for each ?), i have may be a quick workaround for move policy
