### ISSUE TITLE
Question about use Remove-FGTFirewallPolicy

### ISSUE THREAD

**Issue by polo38300** [FortiPower/PowerFGT#131]
Hi

I have a question about the cmdlet Remove-FGTFirewallPolicy, it's possible to use directly the cmdlet Remove-FGTFirewallPolicy  with the parameter name or we are must to make the Get-FGTFirewallPolicy -name XXX |Remove-FGTFirewallPolicy  ?

Thank in advance

Regards,

**Comment by alagoutte** [comment]
Hi,

We try to following powershell guideline/best practice and we need to specify a firewall policy object to remove firewall policy.

**Comment by alagoutte** [comment]
Hi, it is good ?
