### ISSUE TITLE
Failure to connect when post-login-banner is configured

### ISSUE THREAD

**Issue by davehope** [FortiPower/PowerFGT#135]
Tested with various firmware releases (v6.0.8 through 6.4.4),Connect-FGT fails if a post-login-banner is configured.

PowerFGT version 0.5.0
```
Unable to found FGT version
At C:\Program Files\WindowsPowerShell\Modules\PowerFGT\0.5.0\Public\Connection.ps1:176 char:13
+             throw "Unable to found FGT version"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to found FGT version:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to found FGT version
```

If the post-login-banner is removed, login works as expected:

```
config system global
set post-login-banner disable
```

**Comment by alagoutte** [comment]
Hi Dave,

Thanks for the report, i will try !

**Comment by davehope** [comment]
Should it help with troubleshooting.

When the login-banner disabled:
- /logincheck returns a 200 status code and a body of `1document.location="/ng/prompt?viewOnly&redir=%2Fng";`
- /api/v2/monitor/system/firmware returns a 200 status code and the normal JSON body

When the login-banner is enabled:
- /logincheck returns a 200 status code and a body of `1document.location="/logindisclaimer?viewOnly&redir=%2Fng";`. At first glance, the same set of cookies are returned as when login-banner is disabled
- /api/v2/monitor/system/firmware returns a 401 (Unauthorized) response code and HTML body;

**Comment by alagoutte** [comment]
Thanks !

Ok, we need to accept the disclaimer to continue...
from a doc (on FNDN) it is say REST is not supported with post-login-banner...

2 solutions, 
* use the API Token (but not yet supported on PowerFGT)
* add hack to accept the disclaimer => i will see if it is possible

**Comment by davehope** [comment]
I haven't tried it , but wonder if you could check whether the body of the /logincheck Invoke-RestMethod response contains "/logindisclaimer" , if it does then submit a post request to  "/logindisclaimer" with the cookies/headers and a body of:

```
confirm: 1
redir: /ng/
```

And then continue as normal?

**Comment by davehope** [comment]
@alagoutte 
That seems to work. In Connection.ps1:

Aprox line 144:
```
        $uri = $url + "logincheck"
        $iwrResponse = $null
        try {
            $iwrResponse = Invoke-WebRequest $uri -Method POST -Body $postParams -SessionVariable FGT @invokeParams
        }
        catch {
            Show-FGTException $_
            throw "Unable to connect to FortiGate"
        }
```

Approx line 172:
```
        if($iwrResponse.Content -match '/logindisclaimer')
        {
            try {
                Invoke-WebRequest "https://${Server}:${port}/logindisclaimer" -Method "POST" -WebSession $FGT @invokeParams -Body @{confirm = 1} -Headers $headers | Out-Null
            }
            catch {
                throw "Unable to connect"
            }
        }
```

Let me know if you're happy with that fix, if so I'll submit a PR.

**Comment by alagoutte** [comment]
Hi Dave,

Perfect, i write the same type of change and work for me !

Yes, we can push a fix (i will make a review)

i can be nice also to add a test for this (i can look for this too)
