### ISSUE TITLE
Filtering does not work correctly in old operating systems (5.x)

### ISSUE THREAD

**Issue by magarjoba** [FortiPower/PowerFGT#141]
help to disassemble. how to modify your function, or pass it the correct parameters so that it will work correctly on FortiGate-40C v5.2.15 models.
yes i read that your module is only supported from a certain branch. but still there is an API too. and it means there is also its own principle of work.
When uploading default value filtered by WAN Interface Name
##
```powershell
$ fw3 = Connect-FGT 192.168.1.99 -SkipCertificateCheck -DefaultConnection: $ false -Timeout 15
Get-FGTSystemInterface -connection $ fw3 -name wan -filter_type contains | Select name, username, password, status, mode, ip, speed, mtu, mtu-override
```
###
1) this error appears
```powershell
Unable to convert value ".." to type "System.Version". Error: "The input string was not in the correct format."
line: 160 character: 111
+ .... $ ($ version.results.current.minor). $ ($ version.results.current.patch) "
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo: InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId: InvalidCastParseTargetInvocation
```
2) The script is working off, but! as I diagnosed, filtering by the "-name wan" key will not work
instead I get the whole list of interfaces,
No matter what filtering key I put, it simply does not work.

Please help me understand how to debug, for whatever reason, the filter does not work.!

thanks in advance.!

**Comment by magarjoba** [comment]
+ ... .$($version.results.current.minor).$($version.results.current.patch)"
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastParseTargetInvocation
 
my command from test:  Invoke-FGTRestMethod -method "get" -uri "api/v2/monitor/system/interface" -connection $fw3 | Format-Table
-----------------------------------------------------------------------------------------------------------------------

http_method results                                                                                       vdom path   name      action status  serial           version build
----------- -------                                                                                       ---- ----   ----      ------ ------  ------           ------- -----
GET         @{wan1=; wan2=; modem=; internal1=; internal2=; internal3=; internal4=; internal5=; usb-wan=} root system interface select success FGT40C1234567890 v5.2.15   766

**Comment by alagoutte** [comment]
Hi,

the release 5.x is EOL and and it is very limited support of API...

**Comment by alagoutte** [comment]
and about filtering i think, it is coming with 6.0.x

**Comment by magarjoba** [comment]
The API works.
I tested many points both by rules and by interfaces.

the only problem is filtration ...
I'm sure you can somehow do filtering without API. but by means of built-in methods of powershell, but my knowledge is not enough for this. ((((


```
+ ... .$($version.results.current.minor).$($version.results.current.patch)"
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastParseTargetInvocation
 
my command from test2:  Get-FGTSystemInterface -connection $fw3 -name wan  | Select  name, username, password, status, mode , ip , speed, mtu, mtu-override | format-table
-----------------------------------------------------------------------------------------------------------------------

name       username password status mode   ip                          speed  mtu mtu-override
----       -------- -------- ------ ----   --                          -----  --- ------------
GUEST-WIFI          ENC XXXX up     static 10.0.100.1 255.255.255.0 auto  1500 disable     
co-3g-w1            ENC XXXX up     static 0.0.0.0 0.0.0.0             auto  1500 disable     
co-3g-w2            ENC XXXX up     static 0.0.0.0 0.0.0.0             auto  1500 disable     
co-4g-w1            ENC XXXX up     static 0.0.0.0 0.0.0.0             auto  1500 disable     
co-4g-w2            ENC XXXX up     static 0.0.0.0 0.0.0.0             auto  1500 disable     
co-l3-w1            ENC XXXX up     static 0.0.0.0 0.0.0.0             auto  1500 disable     
co-l3-w2            ENC XXXX up     static 0.0.0.0 0.0.0.0             auto  1500 disable     
co-l3-w3            ENC XXXX up     static 0.0.0.0 0.0.0.0             auto  1500 disable     
co-l3-w4            ENC XXXX up     static 0.0.0.0 0.0.0.0             auto  1500 disable     
internal1           ENC XXXX up     static 0.0.0.0 0.0.0.0             auto  1500 disable     
internal2           ENC XXXX up     static 0.0.0.0 0.0.0.0             auto  1500 disable     
internal3           ENC XXXX up     static 0.0.0.0 0.0.0.0             auto  1500 disable     
internal4           ENC XXXX up     static 0.0.0.0 0.0.0.0             auto  1500 disable     
internal5           ENC XXXX up     static 0.0.0.0 0.0.0.0             auto  1500 disable     
lan                 ENC XXXX up     static 192.168.1.99 255.255.255.0  auto  1500 disable     
modem               ENC XXXX down   pppoe  0.0.0.0 0.0.0.0             auto  1500 disable     
ssl.root            ENC XXXX up     static 0.0.0.0 0.0.0.0             auto  1500 disable     
usb-wan             ENC XXXX up     dhcp   0.0.0.0 0.0.0.0             auto  1500 disable     
wan1                ENC XXXX up     dhcp   192.168.0.50 255.255.255.0 auto  1500 disable     
wan2                ENC XXXX up     dhcp   0.0.0.0 0.0.0.0             auto  1500 disable     

```

**Comment by alagoutte** [comment]
for version, can you try this command for i get the output..

```powershell
Invoke-FGTRestMethod -u api/v2/monitor/system/firmware).results.current

name         : FortiOS
id           : current
version      : v7.0.0
major        : 7
minor        : 0
patch        : 0
build        : 66
branch-point : 66
release-type : GA
notes        : https://docs.fortinet.com/document/fortigate/7.0.0/fortios-release-notes/
source       : current
platform-id  : FGT60F
```

for filtering with Powershell, you can use **_Where-Object_**

for example
```powershell
Get-FGTSystemInterface | Where-Object {$_.name -eq "wan1"} | Select  name, username, password, status, mode , ip , speed, mtu, mtu-override  | ft

name username password status mode   ip                           speed  mtu mtu-override
---- -------- -------- ------ ----   --                           -----  --- ------------
wan1                   up     static 192.168.44.144 255.255.255.0 auto  1500 disable
```

**Comment by magarjoba** [comment]
```
Invoke-FGTRestMethod -u api/v2/monitor/system/firmware).results.current
hm.... is this exactly the correct command?

```

 $fs=Connect-FGT 192..168.99 -SkipCertificateCheck -DefaultConnection:$false -Timeout 15
Invoke-FGTRestMethod -method "get" -uri "api/v2/monitor/system/firmware" -connection $fs

```
+ ... .$($version.results.current.minor).$($version.results.current.patch)"
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastParseTargetInvocation
 

http_method : GET
results     : @{current=; available=System.Object[]}
vdom        : root
path        : system
name        : firmware
action      : select
status      : success
serial      : FGT40C0123456789
version     : v5.2.15
build       : 766
```
found a book for previous OS

http://www.tuncaybas.com/FOS_JSON_REST_API_523.pdf

this is work   ` Get-FGTSystemInterface | Where-Object {$_.name -eq "wan1"}`

```
+ ... .$($version.results.current.minor).$($version.results.current.patch)"
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastParseTargetInvocation
 


name         : wan1
username     : 
password     : ENC XXXX
status       : up
mode         : dhcp
ip           : 10.30.20.10 255.255.255.0
speed        : auto
mtu          : 1500
mtu-override : disable
```

**Comment by alagoutte** [comment]
missing a first parenthese
(Invoke-FGTRestMethod -method "get" -uri "api/v2/monitor/system/firmware" -connection $fs).results

and 
(Invoke-FGTRestMethod -method "get" -uri "api/v2/monitor/system/firmware" -connection $fs).results.current

**Comment by magarjoba** [comment]
1)
`+ ... .$($version.results.current.minor).$($version.results.current.patch)"
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastParseTargetInvocation
 

current                                                                                                                                                                                                available
-------                                                                                                                                                                                                ---------
@{name=FortiOS; id=current; version=v5.2.15; build=766; branch-point=766; release-type=GA; notes=http://docs.fortinet.com/d/fortios-5.2.15-release-notes/download; source=current; platform-id=FGT40C} {}       
`
2)
`+ ... .$($version.results.current.minor).$($version.results.current.patch)"
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastParseTargetInvocation
 


name         : FortiOS
id           : current
version      : v5.2.15
build        : 766
branch-point : 766
release-type : GA
notes        : http://docs.fortinet.com/d/fortios-5.2.15-release-notes/download
source       : current
platform-id  : FGT40C`

**Comment by alagoutte** [comment]
Hi

Thanks,i will add a hack/check for detect release 5.x with a warning about missing some feature (like filtering) for next release

**Comment by alagoutte** [comment]
Ok, i try to look this issue, it is only with very very old release (like 5.2...) but will see what it will make...
