### ISSUE TITLE
Bug with diacritics 

### ISSUE THREAD

**Issue by Cool34000** [FortiPower/PowerFGT#158]
Hi,

I'm having a problem with French accented characters.
For example, if I list addresses objects:
```
Get-FGTFirewallAddress | select name

name
----
...
RÃ©seau local
RÃ©seau invitÃ©
SSLVPN_TUNNEL_ADDR1
all
none
...
```
Is there any way to fix this? Or is there anything I can do to convert it on the fly?

**Comment by Cool34000** [comment]
NB: I would like to avoid this kind of solution:

```
(Get-FGTFirewallAddress | select name) | ForEach-Object{
    $($_.name.Replace('Ã©','é'))
}
```

**Comment by alagoutte** [comment]
Bonjour !

i will check ! What powershell version release ? And FGT release ?

**Comment by Cool34000** [comment]
Salut Alexis !

PowerShell v5.1 - Windows 10 20h2
Bug verified on all FortiOS version (from v5.4, to v7.0)

**Comment by alagoutte** [comment]
Thanks

Get the same issue with PS 5 but not with PowerShell 7
I will look for a fix

**Comment by alagoutte** [comment]
Ok found a fix for PS 5 without regression (speed) but not try to add address with accent

**Comment by Cool34000** [comment]
Hi,

Juste tested the fix: it works!
Thanks a lot

**Comment by alagoutte** [comment]
Thanks for feedback ! I will Merge

can you send me your use case ? (You can send by mail if you prefer !)

**Comment by Cool34000** [comment]
> can you send me your use case ? (You can send by mail if you prefer !)

Done!
