### ISSUE TITLE
Upgrade path error

### ISSUE THREAD

**Issue by Cool34000** [FortiPower/PowerFGT#176]
Hi Alexis,

Get-FGTMonitorSystemFirmware -upgrade_paths returns a 404 error.
URI called:
`Invoke-FGTRestMethod -uri api/v2/monitor/system/firmware/upgrade_paths`
URI working:
`Invoke-FGTRestMethod -uri api/v2/monitor/system/firmware/upgrade-paths`

Made a PR for that #177

**Comment by alagoutte** [comment]
Oups... Thanks !

**Comment by alagoutte** [comment]
Fixed with 0.6.1
