### ISSUE TITLE
When using the "Remove-FGTFirewallAddressGroupMember" cmdlet, nothing happens

### ISSUE THREAD

**Issue by t34a** [FortiPower/PowerFGT#189]
Hello
When using the "Remove-FGTFirewallAddressGroupMember" cmdlet, nothing happens:

```powershell
Verbose:
PUT https://FORTIGATE_IP/api/v2/cmdb/firewall/addrgrp/GROUP_NAME? with -1-byte payload
received 303-byte response of content type application/json
https://FORTIGATE_IP:443/api/v2/cmdb/firewall/addrgrp?&filter=name==GROUP_NAME
GET https://FORTIGATE_IP/api/v2/cmdb/firewall/addrgrp?&filter=name==GROUP_NAME with 0-byte payload
received 771-byte response of content type application/json
```
FortiOS version: 6.0.11

**Comment by alagoutte** [comment]
Hi t34a, 

Can you send the full command used ?
You need to use -Member parameter with this cmdlet (and it is true, it is mandatory actually)

**Comment by t34a** [comment]
Hello,  [alagoutte](https://github.com/alagoutte) and thank you for your attention to my question.

here is the part of the script that performs the removal of group members:

		$glgroup = Get-FGTFirewallAddressGroup -name GROUP_NAME
		$glgroupmembers = $glgroup.member
		Foreach ($m in $glgroupmembers)
		{
			$member = Get-FGTFirewallAddress $($m.name)
			Remove-FGTFirewallAddressGroupMember -addrgrp $glgroup -member $member -Confirm -verbose
		}

**Comment by alagoutte** [comment]
Ok,

car you check the $member variable ?

You try to remove all member of a group ?

**Comment by t34a** [comment]
Yes, I understand that it will not work to remove all members of the group, since one must always be in the group. But the script is deleting sequentially,
 so I assumed that it would delete all but one and then give an error, but it does not delete anyone :(

if I do something like this:


$FGT_IP = "FORTIGATE_IP"
$FGT_connection = Connect-FGT $FGT_IP -SkipCertificateCheck -username $con_user -password $con_pass

$glgroup = Get-FGTFirewallAddressGroup -name GROUP_NAME
$glgroup


name          : GROUP_NAME
q_origin_key  : GROUP_NAME
uuid          : 591c064c-b8fa-51ec-ccf6-f6425aed0723
member        : {@{name=04.192.3.126; q_origin_key=04.192.3.126}, @{name=10.34.233.89; q_origin_key=10.34.233.89}}
comment       : updating by Powershell scrpt
visibility    : enable
color         : 1
tagging       : {}
allow-routing : disable

$member = Get-FGTFirewallAddress "04.192.3.126"
$member

name                 : 04.192.3.126
q_origin_key         : 04.192.3.126
uuid                 : 73b2cfd4-b528-51ec-717d-1479eac3d1b6
subnet               : 4.192.3.126 255.255.255.255
type                 : ipmask
country              :
cache-ttl            : 0
sdn                  :
comment              :
visibility           : enable
associated-interface :
color                : 0
filter               :
obj-id               :
list                 : {}
tagging              : {}
allow-routing        : disable

Remove-FGTFirewallAddressGroupMember -addrgrp $glgroup -member $member -Confirm -verbose

: https://FORTIGATE_IP:443/api/v2/cmdb/firewall/addrgrp/GROUP_NAME?
: {
    "member":  [
                   {
                       "name":  "04.192.3.126"
                   },
                   {
                       "name":  "10.34.233.89"
                   }
               ]
}
PUT https://FORTIGATE_IP/api/v2/cmdb/firewall/addrgrp/GROUP_NAME? with -1-byte payload
received 303-byte response of content type application/json
https://FORTIGATE_IP:443/api/v2/cmdb/firewall/addrgrp?&filter=name==GROUP_NAME
GET https://FORTIGATE_IP/api/v2/cmdb/firewall/addrgrp?&filter=name==GROUP_NAME with 0-byte payload
received 771-byte response of content type application/json

name          : GROUP_NAME
q_origin_key  : GROUP_NAME
uuid          : 591c064c-b8fa-51ec-ccf6-f6425aed0723
member        : {@{name=04.192.3.126; q_origin_key=04.192.3.126}, @{name=10.34.233.89; q_origin_key=10.34.233.89}}
comment       : updating by Powershell scrpt
visibility    : enable
color         : 1
tagging       : {}
allow-routing : disable

then as a result there are no errors, but the member of the group 04.192.3.126 remains in it and is not deleted.

**Comment by alagoutte** [comment]
Do you have try with the GUI ?
because if remember, it is not possible to have a group without member...

**Comment by t34a** [comment]
apologize for my English, maybe I'm not expressing myself accurately:

there are currently 2 members in the group GROUP_NAME (04.192.3.126 and 10.34.233.89).

In the example that I gave above, I manually execute commands in Powershell (sequentially):

1. I connect to FortiGate:

$FGT_IP = "FORTIGATE_IP"
$FGT_connection = Connect-FGT $FGT_IP -SkipCertificateCheck -username $con_user -password $con_pass

2. Find the group I need:

$glgroup = Get-FGTFirewallAddressGroup -name GROUP_NAME

3. Output data to make sure $glgroup is not empty:

$glgroup

4. Find the group member I need:

$member = Get-FGTFirewallAddress "04.192.3.126"

5. I output the data to make sure that the $member variable is not empty:

$member

6. in the end, I make sure that all variables contain the correct data about the group and the member of the group that I want to delete,

I am running the delete command:

Remove-FGTFirewallAddressGroupMember -addrgrp $glgroup -member $member -Confirm -verbose

No errors are output to the console.

As a result, if you connect to FortiGate via the GUI, you can make sure that, unfortunately, the required group (GROUP_NAME) also includes 2 members: 04.192.3.126 and 10.34.233.89.

**Comment by t34a** [comment]
I deliberately remove only one member of this group, deliberately leaving the second.

**Comment by alagoutte** [comment]
Ok ok.. 
i will try !

**Comment by t34a** [comment]
thx you :)

**Comment by alagoutte** [comment]
Ok ! found, i need only a string for -member  (and not the object Firewall Address)

You can fix using : 
```powershell
Remove-FGTFirewallAddressGroupMember -addrgrp $glgroup -member $member.name -Confirm -verbose
```

or using pipeline :)
```powershell
$glgroup | Remove-FGTFirewallAddressGroupMember -member $member.name -Confirm -verbose
```

**Comment by t34a** [comment]
Oh, indeed, if you specify a string parameter ($member.name), everything works correctly.
[alagoutte](https://github.com/alagoutte) Thank you very much for the help!!!

**Comment by alagoutte** [comment]
> Oh, indeed, if you specify a string parameter ($member.name), everything works correctly. [alagoutte](https://github.com/alagoutte) Thank you very much for the help!!!

:)
