### ISSUE TITLE
Reg Connect-FGT

### ISSUE THREAD

**Issue by sureshwin006** [FortiPower/PowerFGT#195]
Hi Team I would like to know does the script supports importing CSV files and looping it through each management IP address in CSV file.  

I got the below error when I import it however it works fine when looping it through this way 

```powershell
$unique_device_ips = "172.16.10.10", "172.16.10.11"
Foreach($unique_device_ip in $unique_device_ips) { 
Connect-FGT -Server $unique_device_ip -Credentials $psCred -SkipCertificateCheck
}

Unable to connect to FortiGate
At C:\Program Files\WindowsPowerShell\Modules\PowerFGT\0.6.1\Public\Connection.ps1:181 char:17
+                 throw "Unable to connect to FortiGate"
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Unable to connect to FortiGate:String) [], RuntimeException
+ FullyQualifiedErrorId : Unable to connect to FortiGate
```

Also, I would like to know if is there a way to get export CSV every result from the below modules in one short 

```powershell
Get-FGTMonitorSystemFirmware
Get-FGTSystemGlobal 
Get-FGTMonitorSystemHAPeer
Get-FGTSystemInterface
```
Thanks for the quick reply.

**Comment by alagoutte** [comment]
Hi,

the foreach loop work for me... can you add -verbose ? (all device have the same login/password ?)

you can export using Export-CSV (or using Export-Excel from ImportExcel Module) but need to write your code to get an unique file

**Comment by alagoutte** [comment]
@sureshwin006 it is good ? i can close ?

**Comment by RamakantRThorat** [comment]
I need some help regarding the same issue,  I am connecting the firewall with the IP address 

![image](https://user-images.githubusercontent.com/90766073/208877761-f9e452b2-4f58-4005-b59c-d7ec865f8ac1.png)
I have also used  -skipCertificateCheck -httpOnly

![image](https://user-images.githubusercontent.com/90766073/208880148-c556369b-bbf1-4910-a72f-84ec4170b297.png)

**Comment by RamakantRThorat** [comment]
Please ignore my comment
I am able to connect by specifying -port parameter
