### ISSUE TITLE
Getting Arp Table

### ISSUE THREAD

**Issue by kenaidan** [FortiPower/PowerFGT#203]
Using your module for FortiGate is it possible to get the ARP table? I used the following to pull all the different monitors
**Invoke-FGTRestMethod api/v2/monitor/?action=schema -connection $connection | select -Property directory -ExpandProperty directory**
I found a monitor for ARP which shows the path is network and the name is ARP but I get an error when I use the following

```powershell
Invoke-FGTRestMethod -method "get" -uri "api/v2/monitor/network/arp"

WARNING: The FortiGate API sends an error message:
WARNING: Error description (code): Not Found (404)
WARNING: Error details: {
  "path":"network",
  "name":"arp",
  "action":"",
  "serial":"",
  "version":"v6.0.4",
  "build":231,
  "status":"error",
  "http_status":404
}
Unable to use FortiGate API
At C:\Program Files\WindowsPowerShell\Modules\PowerFGT\0.6.1\Private\RestMethod.ps1:171 char:13
+             throw "Unable to use FortiGate API"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to use FortiGate API:String) [], RuntimeEx 
   ception
    + FullyQualifiedErrorId : Unable to use FortiGate API
```

**Comment by alagoutte** [comment]
Hi @kenaidan,

From FNDN, the "monitor/network/arp", need to have a firmware >= 6.4.3 (it is work me with 7.x, no try with some older release...)
