### ISSUE TITLE
Move-FGTFirewallPolicy function problem

### ISSUE THREAD

**Issue by guillotjeremy** [FortiPower/PowerFGT#210]
Hello, there is a problem with the "**Move-FGTFirewallPolicy**" function.

If no default connection is specified, the function returns an error when calling the last command "**Get-FGTFirewallPolicy -policyid $policy.policyid**" inside the function.

Can you add "**-connection $connection**" at the end of the line.

Thanks.

Regards.

**Comment by alagoutte** [comment]
Thanks ! Good catch, I will fix !
