### ISSUE TITLE
Unexpected behavior with log search - Get-FGTLogTraffic

### ISSUE THREAD

**Issue by madonnassassina** [FortiPower/PowerFGT#227]
**This is my query:**

```powershell
Get-FGTLogTraffic -vdom ISSTN -type disk -subtype forward -dstip 8.8.8.8 -rows 10 -since 30d | select srcip, dstip, dstport, proto | Format-Table
```
**and this is the output:**
```powershell
srcip          dstip        dstport proto
-----          -----        ------- -----
172.20.43.24   10.141.64.2     4343     6
10.140.179.209 10.141.64.2     4343     6
10.140.128.2   10.141.64.2     4343     6
172.20.47.79   10.141.64.2     4343     6
10.140.169.27  10.141.64.6     5274     6
10.127.6.1     10.141.64.7     5274     6
10.140.128.2   10.141.64.7      443     6
10.167.0.2     10.141.20.51    8383     6
172.24.55.150  10.141.64.2     4343     6
172.20.39.14   10.141.64.2     8080     6
```

As you can see there is no trace of the IP 8.8.8.8 in the dstip column

**Comment by alagoutte** [comment]
can you add -verbose to Get-FGTLogTraffic ? (to check url call)

what the FortiOS ?

**Comment by madonnassassina** [comment]
FortiOS Version: 7.0.12


Get-FGTLogTraffic -vdom ISSTN -type disk -subtype forward -dstip 8.8.8.8 -rows 10 -since 30d -verbose | select srcip, dstip, dstport, proto | Format-Table
VERBOSE: https://172.20.xxx.xxx:10443/api/v2/log/disk/traffic/forward?rows=10&vdom=ISSTN&filter=_metadata.timestamp>=1695030713087
VERBOSE: HTTP/1.1 GET with 0-byte payload
VERBOSE: received 15585-byte response of content type application/json
VERBOSE: Content encoding: utf-8

srcip          dstip       dstport proto
-----          -----       ------- -----
172.20.162.137 10.141.64.2    8080     6
172.24.53.202  10.141.64.2    8080     6
172.24.56.56   10.141.64.2    8080     6
172.24.56.163  10.141.64.2    8080     6
172.20.42.120  10.141.64.2    8080     6
172.24.55.201  10.141.64.2    8080     6
10.140.177.152 10.141.64.6    5274     6
172.20.47.79   10.141.64.2    8080     6
172.20.86.154  10.141.64.2    8080     6
172.24.34.11   10.141.64.2    8080     6

**Comment by alagoutte** [comment]
Oups, there is bug/typo, it will fix!

**Comment by madonnassassina** [comment]
Thank you, now it works!

srcip dstip dstport proto

192.168.11.8 8.8.8.8 53 17
192.168.11.8 8.8.8.8 53 17
192.168.11.8 8.8.8.8 53 17
192.168.11.8 8.8.8.8 53 17
192.168.11.8 8.8.8.8 53 17
192.168.11.8 8.8.8.8 53 17
192.168.11.8 8.8.8.8 53 17
192.168.11.8 8.8.8.8 53 17
192.168.11.8 8.8.8.8 53 17
192.168.11.8 8.8.8.8 53 17

**Comment by madonnassassina** [comment]
Closed.
