### ISSUE TITLE
MAC address feature request!

### ISSUE THREAD

**Issue by SogeKing9912** [FortiPower/PowerFGT#228]
Please add feature to add mac address to Address or Address Group

**Comment by alagoutte** [comment]
> Please add feature to add mac address to Address or Address Group

not really planned soon but patch are welcome !

You need to add new parameter (mac type string) https://github.com/FortiPower/PowerFGT/blob/master/PowerFGT/Public/cmdb/firewall/address.ps1#L58

and after add new case 'mac'
https://github.com/FortiPower/PowerFGT/blob/master/PowerFGT/Public/cmdb/firewall/address.ps1#L110

You can look this PR https://github.com/FortiPower/PowerFGT/pull/191 also
