### ISSUE TITLE
add ability to add security profile to firewall policy

### ISSUE THREAD

**Issue by LinuxVCE** [FortiPower/PowerFGT#230]
hi

TNX for your contrectbtion!

can you pls add the ability to add a Security profile to a newly created policy or old policy?

TNX again!

**Comment by alagoutte** [comment]
Hi LinuxVce,

Yes, it is not yet available... and need some work for adding

What type of Security Profile do you need ?

**Comment by alagoutte** [comment]
> hi TNX
> 
> IPS , AV, WebFilter, choosing Certificate in the policy. TNX!!!

by choosing certificate, it is inspecting mode ? 

i check and there is not yet -data parameter for FGTFirewallPolicy, i need to make modification for adding this
