### ISSUE TITLE
Content-Type required but not specified for Invoke-RestMethod

### ISSUE THREAD

**Issue by kevinsaucier** [FortiPower/PowerFGT#246]
Not sure if this is just me, but it seems like a PowerShell update seems to have broken Power-FGT.  I've been using Power-FGT for quite a while with no issues (other than my own poorly written code 😁) but I started having issues managing group membership on Friday (coincidentally, my PowerShell auto updates every Friday).  I was able to add/remove an address object, but adding/removing either an address or address group to/from another group was failing.  I had been using 0.7 but just updated to 0.8 and had the same issue.

I removed the try/catch from the IF on line 192 in RestMethod.ps1 and was able to get the following:

Invoke-RestMethod: C:\Users\kevin\Documents\PowerShell\Modules\PowerFGT\0.8.0\Private\RestMethod.ps1:199
Line |
 199 |  … $response = Invoke-RestMethod $fullurl -Method $method -body (Convert …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The given key 'Content-Type' was not present in the dictionary.
VERBOSE: https://<firewall>/api/v2/cmdb/firewall/addrgrp?&filter=name==<GroupName>
VERBOSE: Requested HTTP/1.1 GET with 0-byte payload
VERBOSE: Received HTTP/1.1 response of content type application/json of unknown size
VERBOSE: Content encoding: utf-8

By adding this line before the try/catch, it seems to have resolved the issue:

$headers += @{"Content-Type"="text/json"}

```
  #Display (Full)url when verbose (no longer available with PS 7.2.x...)
        Write-Verbose $fullurl
$headers += @{"Content-Type"="text/json"}
        try {
            if ($body) {
```

**Comment by alagoutte** [comment]
Hi @kevinsaucier 

What powershell release do you have now ?

**Comment by kevinsaucier** [comment]
> Hi @kevinsaucier
> 
> What powershell release do you have now ?

Duh....sorry, I completely meant to include that. 

Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by alagoutte** [comment]
Always using 7.4.1 and not issue for me...

i will look for update !

**Comment by kevinsaucier** [comment]
Thanks!  I was able to find some logs and my code was still working with 7.4.2 for a bit, so that may not be the trigger.....maybe just coincidence.  I did find someone else from over a month ago with the same error message.  

https://github.com/orgs/community/discussions/110246

Also, I've modified my address.ps1 file to accept a parameter for color.  I don't think that would be an issue, given that I didn't modify the addressgroup.ps1 file, but figured I'd mention it.

[address.txt](https://github.com/FortiPower/PowerFGT/files/14971838/address.txt)

**Comment by alagoutte** [comment]
i check the powershell 7.4.2 release note but only some revert stuff  about content-type : https://github.com/PowerShell/PowerShell/releases/tag/v7.4.2, i will try to update to 7.4.2 for try

But not a problem for adding content-type (application/json ?) to headers

For color, you can push a PR for adding (need to add also some tests, look Tests/integration/FirewallAddress.Tests1.ps1)

**Comment by alagoutte** [comment]
@kevinsaucier i have reproduce the issue with PowerShell 7.4.2, i will make more Tests

**Comment by kevinsaucier** [comment]
> @kevinsaucier i have reproduce the issue with PowerShell 7.4.2, i will make more Tests

Great!  Glad it's not just me or my code.   Thanks for the quick response!

As for the color PR, I plan to push it at some point, but I had only made the changes to the Address file and I had read a while ago that you wanted to keep all types consistent so I wanted to make the change to all items before pulling the PR.

**Comment by alagoutte** [comment]
> > @kevinsaucier i have reproduce the issue with PowerShell 7.4.2, i will make more Tests
> 
> Great! Glad it's not just me or my code. Thanks for the quick response!
> 
> As for the color PR, I plan to push it at some point, but I had only made the changes to the Address file and I had read a while ago that you wanted to keep all types consistent so I wanted to make the change to all items before pulling the PR.

For color, you can already push your change for address (with Tests) and after for AddressGroups and other ;-)
