### ISSUE TITLE
PS 7.4.2, restmethod.ps1 ContentType application/json

### ISSUE THREAD

**Issue by jdesl** [FortiPower/PowerFGT#251]
Hello,

I had to add -ContentType application/json for a quick fix when calling:

get-FGTFirewallAddressGroup -name 'group' -vdom 'master' | Add-FGTFirewallAddressG-memberroupMember  'member' -vdom 'master'

restmethod.ps1
-ContentType application/json

line 199:
$response = Invoke-RestMethod $fullurl -Method $method -body (ConvertTo-Json $body -Depth 10 -Compress) -Headers $headers -WebSession $sessionvariable @invokeParams **-ContentType application/json**

PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT

**Comment by alagoutte** [comment]
Fixed with release 0.8.1
