### ISSUE TITLE
Add Timeout Functionality to Connect-FGT

### ISSUE THREAD

**Issue by chisho21** [FortiPower/PowerFGT#55]
Loving this Module so far!

Running to an issue where a few clients will not connect and Connect-FGT will not time out.

It looks like the Invoke-WebRequest in "Connection.ps1" on line 135 needs a -timeout added and parameterized with a default.

The default timeout of Invoke-WebRequest seems to be over 5+ minutes.

**Comment by alagoutte** [comment]
Hi @chisho21 

Thanks for PR, it will look

Can you explain when you get the issue ? (by [default timeout](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-6#parameters) is set to 0 -> indefinite )

**Comment by chisho21** [comment]
I'm doing a foreach loop through ~100 remotely managed Fortigates in a separate script. Devices that are off or are not Fortigates cause that script to just hang and wait indefinitely.

**Comment by alagoutte** [comment]
Ok nice !

do you have a try / catch ?

May be set bigger timeout (it is very fast 5 sec)

What the use case ? (you can send me a mail (you can found on top of ps file))

**Comment by chisho21** [comment]
I do have a try / catch in my code. But due to never erroring the catch is never triggers due to lack of time out. Tried (and failed) to accomplish with powershell jobs, but realized this was probably the more elegant solution.

**Comment by alagoutte** [comment]
Fixed on #56 

Thanks !
I will be available on next release (for end of year i hope)
