### ISSUE TITLE
VMware.VimAutomation.Common is required to use module

### ISSUE THREAD

**Issue by sledgehoe** [FortiPower/PowerFGT#71]
Hi,

when importing the module hte first time you will get following error:

C:\Program Files\WindowsPowerShell\Modules\PowerFGT\0.4.0\PowerFGT.psm1 : Failed to import function C:\Program
Files\WindowsPowerShell\Modules\PowerFGT\0.4.0\Public\Deploy.ps1: Das Skript "Deploy.ps1" kann nicht ausgeführt
werden, da die folgenden in den "#requires"-Anweisungen des Skripts angegebenen Module fehlen:
VMware.VimAutomation.Common.
In Zeile:1 Zeichen:1
+ Import-Module PowerFGT
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,PowerFGT.psm1

This can be solved by installing this missing module using:
**Install-Module VMware.VimAutomation.Common**

Maybe this can be fixed on initial Module installation.

Best Regards
Gerald Gaugusch

**Comment by alagoutte** [comment]
Hi Gerald,

Thanks for feedback.
Oups, it is only need if you want to Deploy a FGT VM, (not mandatory for rest of module)
i will change the require check..
