### ISSUE TITLE
Allow unnamed Firewall Policy

### ISSUE THREAD

**Issue by chrisvanmeer** [FortiPower/PowerFGT#75]
Hi, could you please make the firewall policy name not required? Or let me know how to disable the name property from being required

**Comment by alagoutte** [comment]
Hi,

Yes, for the moment, the policy name is required...

You can try to set mandatory to false here https://github.com/FortiPower/PowerFGT/blob/master/PowerFGT/Public/cmdb/firewall/policy.ps1#L65

Remove check test https://github.com/FortiPower/PowerFGT/blob/master/PowerFGT/Public/cmdb/firewall/policy.ps1#L115

and comment add the name of on policy https://github.com/FortiPower/PowerFGT/blob/master/PowerFGT/Public/cmdb/firewall/policy.ps1#L158

it will look for next release to add support of unnamed policy

**Comment by alagoutte** [comment]
it is working ?

**Comment by cvanmeer** [comment]
Well, I am a beginning Powershell scripter, I don't know how to modify an existing module (I installed your Module through psgallery) and use it locally. For now I fix it by using a counter and using that in the name.

**Comment by alagoutte** [comment]
> 
> Well, I am a beginning Powershell scripter, I don't know how to modify an existing module (I installed your Module through psgallery) and use it locally. For now I fix it by using a counter and using that in the name.

Ok, you need to modified directly module :
C:\Users\MyUser\Documents\WindowsPowerShell\Modules

(Replace MyUser by your user)

**Comment by cvanmeer** [comment]
Thanks, for me the location is /root/.local/share/powershell/Modules (running my code inside of a VSCode Powershell container). Modifying the files you said worked, but has to be redone after a container rebuild in this setup.

**Comment by alagoutte** [comment]
> Thanks, for me the location is /root/.local/share/powershell/Modules (running my code inside of a VSCode Powershell container). Modifying the files you said worked, but has to be redone after a container rebuild in this setup.

Yes...
the container is public ?
i will make change for next release

**Comment by alagoutte** [comment]
Reopen because i found a issue with policy return...
