### ISSUE TITLE
Filtering on interface properties

### ISSUE THREAD

**Issue by cvanmeer** [FortiPower/PowerFGT#76]
I am trying to retrieve all interfaces belonging to a certain VDOM:  
  
```powershell
`$SourceInterfaces = Get-FGTSystemInterface -connection $SourceConnection -filter_attribute vdom -filter_type equal -filter_value $SourceVDOM`  
  ```

But this doesn't seem to work.

**Comment by alagoutte** [comment]
Hi,

Do you have a error ?

can you try
```powershell
$SourceInterfaces = Get-FGTSystemInterface -connection $SourceConnection  -vdom sourceVDOM
```

**Comment by cvanmeer** [comment]
No error, it just collects all (95 in my case) interfaces.  
Your proposal doesn't give different results.  
  
I now work around it, by collecting all interfaces, loop through them and if the VDOM matches $SourceVDOM, put it in a new array.

**Comment by alagoutte** [comment]
Strange... it will check

What FGT release do you are using ?

**Comment by cvanmeer** [comment]
v5.4.4,build1117,170209 (GA)

**Comment by alagoutte** [comment]
> v5.4.4,build1117,170209 (GA)

Oh, it is old may be some bug on filtering stuff...

**Comment by alagoutte** [comment]
I try with 6.2.x and 

```powershell
 Get-FGTSystemInterface  -filter_attribute vdom -filter_type equal -filter_value myVDOM
```
and work for me
