### ISSUE TITLE
Use case for "confirm-*" cmdlets?

### ISSUE THREAD

**Issue by poundy** [FortiPower/PowerFGT#82]
Hey there, just checked and couldn't see any info on how the confirm-* cmdlets were expected to be used so thought I'd ask!

**Comment by alagoutte** [comment]
Hi,

Confirm-FGT* cmdlets is internal cmdlet for check type of object (Need to don't be export... but it is more easy for dev to be export..)

**Comment by alagoutte** [comment]
can be close ?

**Comment by poundy** [comment]
Once I cracked open the code, I could see they were simply checking whether a passed object had relevant properties to match the object-type expected (ie minimum properties that the FGT needs, plus any indicators that would imply something wasn't what was passed)
