### ISSUE TITLE
Return object of Connect-FGT is not an object

### ISSUE THREAD

**Issue by poundy** [FortiPower/PowerFGT#84]
The return object of Connect-FGT isn't an object, but a set of objects. 

I'd like to have been able to do the following: 
```powershell
$conn = connect-fgt FGT-A.fqdn.com -SkipCertificateCheck -Credentials $fwcred
$conn += connect-fgt FGT-B.fqdn.com -SkipCertificateCheck -Credentials $fwcred
```
and then later do foreach operations on that.  But I found that connection object returned isn't really an object...

**Comment by alagoutte** [comment]
```powershell

$conn.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Hashtable                                System.Object
```

it is hashtable object.. 
It will see what i can make for this case...

**Comment by alagoutte** [comment]
can you try this :

```powershell
$conn = @()
$conn += connect-fgt FGT-A.fqdn.com -SkipCertificateCheck -Credentials $fwcred
$conn += connect-fgt FGT-B.fqdn.com -SkipCertificateCheck -Credentials $fwcred
```

**Comment by poundy** [comment]
the behaviour of your second suggestion will work for me, thanks.  The $conn object is now "strange" when you enumerate it but it works.  Enumerating each element behaves as expected, but enumerating the whole just flows the elements together (usually you'd see a whitespace line between individual elements)

PS C:\brett> $conn

Name                           Value                                                                              
----                           -----                                                                              
headers                        {X-CSRFTOKEN}                                                                      
vdom                                                                                                              
invokeParams                   {UseBasicParsing, DisableKeepAlive, TimeoutSec}                                    
server                         1-fg-mgmt                                                                    
httpOnly                       False                                                                              
port                           443                                                                                
session                        Microsoft.PowerShell.Commands.WebRequestSession                                    
headers                        {X-CSRFTOKEN}                                                                      
vdom                                                                                                              
invokeParams                   {UseBasicParsing, DisableKeepAlive, TimeoutSec}                                    
server                         2-fg-mgmt                                                                    
httpOnly                       False                                                                              
port                           443                                                                                
session                        Microsoft.PowerShell.Commands.WebRequestSession

**Comment by alagoutte** [comment]
Yes, it is strange but working ;-) (it is a array of object...)

**Comment by alagoutte** [comment]
can be close ?

**Comment by poundy** [comment]
I have no problem closing it, I'll do that now. The first "+=" behaviour is not what I would call normal, but the above workaround works fine for my use cases
