### ISSUE TITLE
Add VIPGRP functions

### ISSUE THREAD

**Issue by poundy** [FortiPower/PowerFGT#88]
Like *AddressGroup, we need *VipGroup functions

**Comment by poundy** [comment]
I've coded and done some basic tests on a candidate for this.  You were right, the core was there from AddressGroup so there wasn't too many things that I needed to grapple with.  I'll fix up the document I edited earlier and submit the PR

**Comment by poundy** [comment]
#89

**Comment by alagoutte** [comment]
it is now merged and need now to publish a new release.... :)
