### ISSUE TITLE
Unable to remove member from group

### ISSUE THREAD

**Issue by PaskDrolet** [FortiPower/PowerFGT#90]
Hi!!

I'm trying to remove a member from an address group and that doesn't work. I see when verbose mode is enable that the member I'm trying to remove is not listed but after the command, it was listed again!!

command used: 
```powershell
`Get-FGTFirewallAddressGroup -name "Windows2008" | Remove-FGTFirewallAddressGroupMember -verbose -member $Inputmachine`

Output: 
`COMMENTAIRES : {
    "member":  {
                   "name":  "04chrtr00035.04trvr08.reg04.rtss.qc.ca_fqdn"
               }
}
COMMENTAIRES : PUT https://10.38.220.221/api/v2/cmdb/firewall/addrgrp/Windows 2008?&vdom=WAN with -1-byte payload
COMMENTAIRES : received 278-byte response of content type application/json
COMMENTAIRES : GET https://10.38.220.221/api/v2/cmdb/firewall/addrgrp?&vdom=WAN&filter=name==Windows 2008 with 0-byte payload
COMMENTAIRES : received 798-byte response of content type application/json

name          : Windows 2008
q_origin_key  : Windows 2008
uuid          : d5539d2c-621e-51ea-61ad-45d8d89f136d
member        : {@{name=04chrtr00035.04trvr08.reg04.rtss.qc.ca_fqdn; q_origin_key=04chrtr00035.04trvr08.reg04.rtss.qc.ca_fqdn}, @{name=mcq04000389; q_origin_key=mcq04000389}}
comment       : 
visibility    : enable
color         : 0
tags          : {}
allow-routing : disable`
```
Pascal

**Comment by alagoutte** [comment]
Bonjour Pascal,

What FGT release ?, you are using VDOM ?

What the configuration before ? (for i try to reproduce the issue...)

**Comment by poundy** [comment]
The URI has VDOM=WAN listed in it, so yes there's VDOMs involved.... also going to try to repro it

**Comment by PaskDrolet** [comment]
Hi,

Yes I'm using VDOM. Here's the connection string: 
Connect-FGT -SkipCertificateCheck 10.38.220.221 -vdom WAN

Thanks for your help!!
Pascal

**Comment by alagoutte** [comment]
What the config ?  (and FGT release ?)

Do you have check the "case" ?

**Comment by PaskDrolet** [comment]
FGT Release: 5.6.6
PowerFGT: 0.4.0

I don't have any prompt to check the case. I've it when I delete an address entry. By the way, is there a method to remove confirmation on deletion? 

My script for testing:
`Import-Module PowerFGT

# Connexion au Fortigate par l'adresse du HA
Connect-FGT -SkipCertificateCheck 10.38.220.221 -vdom WAN

$Inputmachine = "mcq04000389"

# Enlever adresse d'un groupe
Get-FGTFirewallAddressGroup -name "Windows2008" | Remove-FGTFirewallAddressGroupMember -verbose -member $Inputmachine

Disconnect-FGT`

The entry mcq04000389 exist on the VDOM and is linked to the address group.

**Comment by alagoutte** [comment]
Ok, i have reproducte the issue (it is coming when there is only 2 member and remove last one...)

**Comment by PaskDrolet** [comment]
On my side, the group as 1 member left in it after removing the one in the script!

**Comment by alagoutte** [comment]
> 
> 
> On my side, the group as 1 member left in it after removing the one in the script!

Yes, but i push the wrong format (need to be an array)
