### ISSUE TITLE
Create new policy with defined PolicyID

### ISSUE THREAD

**Issue by poundy** [FortiPower/PowerFGT#92]
API details for Add Firewall Policy?  
My use case needs me to explicitly set policy IDs to maintain configuration drift, and the current implementation doesn't allow for this; I've tested out adding this using the REST method and adding the PolicyID property, but that hasn't seemed to work. So I'm wondering if anyone has access to real documentation on the API and can see whether there's an option to do this?

**Comment by alagoutte** [comment]
Hi @poundy, there is more info available https://fndn.fortinet.net but no sure it is possible to set the policy ID...

**Comment by poundy** [comment]
Developer network is stupidly restrictive. You need two FTNT employees to vouch for you, which I don't have..... 
That's a bit of a pain if you can't set the policy ID.  For my use case I have two FGT clusters that have largely matching configurations in terms of Addresses, address groups, VIPs, VIPGRPs, and policies so that if we have an internet link failure that BGP manages, all services will continue to run. We've used a script to detect variance, which is easiest to do comparisons when the policy IDs match. And it's kind of weird because that is the key item within the CLI when you edit a policy or create a new policy....

**Comment by alagoutte** [comment]
Yes, i known for access to FTNT...

I will check for Policy ID

**Comment by alagoutte** [comment]
From FTNT, it look will be possible :

![FTNT_PolicyID](https://user-images.githubusercontent.com/1098542/76741863-87c42c00-6770-11ea-9b54-681cfdbd3228.PNG)

**Comment by poundy** [comment]
Yay, I have it (somewhat) working. I had bad capitalisation I think !

I'll amend my fork with the changes, once I test my code (and get the duplicate checking working that's harder than I thought - type confusion!) so it shows up in the PR and hopefully can make it for the 0.5.0 milestone. 

And in the meantime I am trying to find an avenue into FNDN

**Comment by alagoutte** [comment]
Hi @poundy do you think push this change ? (i will write very soon test for Policy)

**Comment by poundy** [comment]
Yes please, we should get this incorporated. I use this mode regularly, as I manually maintain two distinct FGTs with matching rules and use the PolicyID as the key (create the policy programmatically on both FGTs at once with same PolicyID, so I know they are strictly matching)

My problem is that I can't figure out how to achieve that, my GIT fu is weak. I think that since my repo has some commits ahead of the main repo, and I did this development in a separate branch, I can't really figure out how to unwind all that and not lose content and not break existing commits. Any and all suggestions welcomed !!!

**Comment by alagoutte** [comment]
i reopen the issue for don't forget this issue (and i will also look to can set also uuid

for Github skill, you can look https://lab.github.com/

but on this case, it is easy ! fork this repo (it is already the case)
clone on your local machine

`git clone https://github.com/yourusername/PowerFGT.git`

go on the PowerFGT folder
`cd PowerFGT`

create a new local branch
`git branch -b MyFeatureBranch`

make local change and commit
`git commit -a -m "My Feature"`

push on your repo
`git push"`
(may be ask to set origin)

and after go on Github for make PR to this repo

If you need to update to last upstream (this repo)

Add FortiPower to upstream (for update/rebase)
`git remote add upstream https://github.com/FortiPower/PowerFGT.git`

Update source code (your branch and FortiPower Branch)
`git fetch --all`

Update your local branch with rebase
`git rebase upstream/master`
You may need to fix some merge issue (but git will say what command do you need to use !)

@Tuurtje, can be help for you too
